apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    io.shyrka.erebus/archetype-name: "${project.artifactId}"
    io.shyrka.erebus/archetype-version: "${project.version}"
spec:
  selector:
    matchLabels:
      app: tom-operator
  template:
    metadata:
      labels:
        app: tom-operator
    spec:
      serviceAccountName: tom-operator
      securityContext:
      #  runAsUser: 1234
      #  runAsGroup: 1234
      #  fsGroup: 1234
      #  runAsNonRoot: true
      containers:
      - name: tom-operator
        imagePullPolicy: ${jkube-deployment-spec-template-spec-containers-imagepullpolicy}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          securityContext:
          #  allowPrivilegeEscalation: false
          #  readOnlyRootFilesystem: true