---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    io.shyrka.erebus/archetype-name: "tom"
    io.shyrka.erebus/archetype-version: "1.0-SNAPSHOT"
  name: tom-operator
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - service/status
  - deployment/status
  - pods/status
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "io.github.shyrkaio.sample"
  resources:
  - tom
  - tom/status
  verbs:
  - '*'