apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
  labels:
    #for reference see https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
    app.kubernetes.io/component: tomcat-server
    app.kubernetes.io/part-of: ""
    app.kubernetes.io/managed-by: "" # used for filtering of Deployments created by the controller
    app.kubernetes.io/created-by: "" # used watching Deployments created by the controller
  ownerReferences: # used for finding which Tomcat does this Deployment belong to
    - apiVersion: apps/v1
      kind: MySimpleOp
      name: ""
      uid: ""
spec:
  selector:
    matchLabels:
      app: ""
  replicas: 0
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
        - name: tomcat
          image: tomcat:8.0
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
          ports:
            - name: http8080
              containerPort: 8080

